dir = 0
print((dir + 1) % 4)
print((dir + 2) % 4)
print((dir + 3) % 4)
print((dir + 4) % 4)
print((dir + 5) % 4)
print((dir - 1) % 4)
print((dir - 2) % 4)
print((dir - 3) % 4)
print((dir - 4) % 4)
print((dir - 5) % 4)